name: Build/Verify/Publish MR/Release

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  precheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Cache Android SDK
        id: cache-android
        uses: actions/cache@v5
        with:
          path: /root/.android/sdk
          key: android

      - name: Set up Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: build-tools;35.0.0 platforms;android-36 platforms;android-37.0
          log-accepted-android-sdk-licenses: false
          cmdline-tools-version: 14742923

#      - name: Run detekt
#        run: |
#          cd Kuroba
#          chmod +x ./gradlew
#          ./gradlew detekt -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=8g"

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Cache Android SDK
        id: cache-android
        uses: actions/cache@v5
        with:
          path: /root/.android/sdk
          key: android

      - name: Set up Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: platform-tools build-tools;35.0.0 platforms;android-36 platforms;android-37.0
          log-accepted-android-sdk-licenses: false
          cmdline-tools-version: 14742923

      - name: Instal aapt2 for arm64
        run: |
          wget https://github.com/SuperJMN/DotnetAndroidArm64Shims/releases/download/36.1.53/shims-linux-arm64-36.1.53.tar.gz
          tar -xzf shims-linux-arm64-36.1.53.tar.gz
          chmod +x aapt2
          mv aapt2 /usr/bin
          mv libMono.Unix.so libZipSharpNative-3-3.so /usr/lib

      - name: Run unit-tests
        run: |
          cd Kuroba
          chmod +x ./gradlew
          ./gradlew testDebugUnitTest --stacktrace -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=8g"

  publish-beta:
    if: github.event_name == 'push'
    needs: [precheck, unit-test]
    uses: ./.github/workflows/build-setup.yml
    with:
      publish-type: beta
    secrets: inherit

  publish-stable:
    if: github.event_name == 'push'
    needs: [precheck, unit-test]
    uses: ./.github/workflows/build-setup.yml
    with:
      publish-type: stable
    secrets: inherit
